import type { Spot } from './types';

export const MOCK_SPOTS: Spot[] = [
  {
    id: '1',
    name: '陽だまりわんぱく公園',
    address: '東京都練馬区光が丘',
    rating: 4.5,
    reviewCount: 128,
    image: 'https://picsum.photos/600/400?random=1',
    tags: ['無料', '大型遊具', '広々'],
    priceCategory: 'free',
    facilities: {
      toilet: true,
      parking: true,
      diaper: true,
      indoor: false,
      water: true,
      largePlayground: true,
      stroller: true,
    },
  },
  {
    id: '2',
    name: 'キッズ未来科学館',
    address: '東京都板橋区常盤台',
    rating: 4.2,
    reviewCount: 85,
    image: 'https://picsum.photos/600/400?random=2',
    tags: ['格安', '屋内', '学び'],
    priceCategory: 'cheap',
    facilities: {
      toilet: true,
      parking: false,
      diaper: true,
      indoor: true,
      water: false,
      largePlayground: false,
      stroller: true,
    },
  },
  {
    id: '3',
    name: '森の冒険アスレチック',
    address: '神奈川県横浜市旭区',
    rating: 4.8,
    reviewCount: 340,
    image: 'https://picsum.photos/600/400?random=3',
    tags: ['有料', 'アスレチック', '自然'],
    priceCategory: 'paid',
    facilities: {
      toilet: true,
      parking: true,
      diaper: false,
      indoor: false,
      water: false,
      largePlayground: true,
      stroller: false,
    },
  },
  {
    id: '4',
    name: 'せせらぎ親水公園',
    address: '東京都世田谷区',
    rating: 4.0,
    reviewCount: 56,
    image: 'https://picsum.photos/600/400?random=4',
    tags: ['無料', '水遊び', 'ピクニック'],
    priceCategory: 'free',
    facilities: {
      toilet: true,
      parking: false,
      diaper: true,
      indoor: false,
      water: true,
      largePlayground: false,
      stroller: true,
    },
  },
  {
    id: '5',
    name: 'ドリームランド室内パーク',
    address: '埼玉県さいたま市',
    rating: 3.8,
    reviewCount: 42,
    image: 'https://picsum.photos/600/400?random=5',
    tags: ['有料', '雨の日OK', 'ボールプール'],
    priceCategory: 'paid',
    facilities: {
      toilet: true,
      parking: true,
      diaper: true,
      indoor: true,
      water: false,
      largePlayground: true,
      stroller: true,
    },
  },
];